# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,30)
# 30 ko exclude krke.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [7]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,20,10)
# 0 to 20  m  10 number ko lena h. same space m. means 9 space banana h.

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [10]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#Create an array of the given shape and populate it with
#random samples from a uniform distribution
#over ``[0, 1)``.

np.random.rand(2,4)

array([[0.10971164, 0.12675245, 0.73228081, 0.1871142 ],
       [0.12290907, 0.36254496, 0.85313747, 0.98549185]])

In [13]:
np.random.rand(2,7)

array([[0.72198559, 0.27781814, 0.72801722, 0.31895704, 0.01106122,
        0.4964034 , 0.67979644],
       [0.35186081, 0.10037431, 0.25874562, 0.14602334, 0.56671397,
        0.71964054, 0.74305619]])

In [14]:
np.random.randn(2,4)

array([[-1.00553939, -1.05820748,  0.77741314, -1.86245747],
       [ 0.82747742,  1.28730021, -1.77519885, -0.63336331]])

In [15]:
np.random.randn()

-0.2955064993154996

In [16]:
np.random.randint(2,10)

2

In [17]:
np.random.randint(2,10,size = 10) # yhan 10 ko exclude krke

array([6, 7, 5, 2, 5, 3, 6, 6, 7, 2])

In [18]:
np.random.randint(20,56,100)

array([30, 40, 38, 49, 27, 22, 32, 32, 46, 53, 47, 49, 50, 27, 20, 41, 34,
       25, 26, 24, 25, 43, 41, 27, 37, 43, 37, 45, 27, 23, 28, 52, 20, 45,
       55, 33, 53, 37, 24, 53, 50, 26, 27, 34, 40, 42, 31, 38, 41, 41, 31,
       55, 54, 39, 20, 44, 29, 20, 41, 43, 42, 22, 50, 40, 27, 39, 44, 22,
       49, 33, 37, 47, 46, 27, 51, 46, 34, 37, 35, 48, 43, 55, 31, 31, 21,
       27, 42, 52, 23, 54, 33, 45, 35, 30, 27, 49, 21, 50, 29, 39])

In [19]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
rand_array=np.random.randint(0,100,20)
rand_array

array([69, 77, 26, 94, 75, 29, 97, 36, 77, 93, 29, 20, 21, 48, 48, 90,  6,
        2, 93, 47])

In [21]:
sample_array.reshape(3,10)
# existing array ko given rows and columns m bna dega.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
rand_array.max()

97

In [23]:
rand_array.argmax()

6

In [24]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
sample_array.shape

(30,)

In [26]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
sample_array.dtype

dtype('int32')

In [28]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a=np.random.rand(2,3)
a

array([[0.55514802, 0.4712482 , 0.39243759],
       [0.33669867, 0.52804002, 0.27245895]])

In [31]:
a.T

array([[0.55514802, 0.33669867],
       [0.4712482 , 0.52804002],
       [0.39243759, 0.27245895]])

In [32]:
import numpy as np

In [33]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
sample_array[8]

18

In [35]:
sample_array[2:5]

array([12, 13, 14])

In [36]:
sample_array[[2,5]]


array([12, 15])

In [37]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [38]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [39]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [40]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [41]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [42]:
sample_matrix[0][2]

1

In [43]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [44]:
sample_matrix[2]

array([56, 76, 24,  7])

### Custom indexing

In [45]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [46]:
sample_matrix[:,(3,2)]
# sare rows and column 3 then column 2.

array([[23,  1],
       [33, 32],
       [ 7, 24]])

In [47]:
sample_matrix[(1,2),(3,2)] # phle 3rd column and then 2nd column 
#but 3rd column m 1st element and 2nd column m 2nd element  

array([33, 24])

In [48]:
sample_matrix[(0,2),(2,0)]

array([1, 6])

###  Selection techniques

In [49]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [51]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [53]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [54]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [56]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [57]:
np.max(sample_array)

30

In [58]:
np.min(sample_array)

1

In [59]:
np.argmax(sample_array) # giving index no of maximum value in sample_array 

29

In [60]:
np.argmin(sample_array)

0

In [61]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [62]:
np.std(sample_array)

8.65544144839919

In [63]:
np.var(sample_array)


74.91666666666667

In [64]:
np.mean(sample_array)

15.5

In [65]:
array=np.random.randn(3,6)
array

array([[ 0.96795547,  0.59312456, -1.0001106 , -0.80779961,  0.63692527,
         1.31960047],
       [ 1.47197429, -0.39982776,  2.9236041 , -0.28426691,  0.68232968,
         1.61503306],
       [ 0.00613651, -1.32398124, -1.542758  , -0.2859709 ,  0.1286479 ,
         0.17205252]])

In [66]:
np.round(array,decimals=2)

array([[ 0.97,  0.59, -1.  , -0.81,  0.64,  1.32],
       [ 1.47, -0.4 ,  2.92, -0.28,  0.68,  1.62],
       [ 0.01, -1.32, -1.54, -0.29,  0.13,  0.17]])

In [67]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [68]:
import pandas as pd

In [69]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}


In [70]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [71]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [72]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [73]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [74]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [75]:
sports1['cricket']

1

In [76]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [77]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [78]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

#df1['Score3']



Score1    Score2    Score3    Score4    Score5
A  0.399631  0.223939  0.270573  0.551676  0.369628
B  0.447741  0.274916  0.519281  0.003205  0.511999
C  0.626007  0.434210  0.208684  0.226580  0.662761
D  0.848760  0.886848  0.618104  0.648377  0.273240
E  0.299416  0.793691  0.444728  0.017175  0.459145
F  0.611408  0.706270  0.797793  0.658284  0.608447
G  0.331133  0.906085  0.705067  0.678309  0.221777
H  0.794974  0.393850  0.278573  0.938164  0.146730

In [79]:
df1['Score3']

A    0.270573
B    0.519281
C    0.208684
D    0.618104
E    0.444728
F    0.797793
G    0.705067
H    0.278573
Name: Score3, dtype: float64

In [80]:
df1[['Score2','Score1']]

#df1['Score6']=df1['Score1']+df1['Score2']
#df1



Score2    Score1
A  0.223939  0.399631
B  0.274916  0.447741
C  0.434210  0.626007
D  0.886848  0.848760
E  0.793691  0.299416
F  0.706270  0.611408
G  0.906085  0.331133
H  0.393850  0.794974

In [81]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.399631  0.223939  0.270573  0.551676  0.369628  0.623570
B  0.447741  0.274916  0.519281  0.003205  0.511999  0.722657
C  0.626007  0.434210  0.208684  0.226580  0.662761  1.060217
D  0.848760  0.886848  0.618104  0.648377  0.273240  1.735608
E  0.299416  0.793691  0.444728  0.017175  0.459145  1.093107
F  0.611408  0.706270  0.797793  0.658284  0.608447  1.317678
G  0.331133  0.906085  0.705067  0.678309  0.221777  1.237218
H  0.794974  0.393850  0.278573  0.938164  0.146730  1.188823

In [82]:
df1.drop('Score5',axis=1)



Score1    Score2    Score3    Score4    Score6
A  0.399631  0.223939  0.270573  0.551676  0.623570
B  0.447741  0.274916  0.519281  0.003205  0.722657
C  0.626007  0.434210  0.208684  0.226580  1.060217
D  0.848760  0.886848  0.618104  0.648377  1.735608
E  0.299416  0.793691  0.444728  0.017175  1.093107
F  0.611408  0.706270  0.797793  0.658284  1.317678
G  0.331133  0.906085  0.705067  0.678309  1.237218
H  0.794974  0.393850  0.278573  0.938164  1.188823

In [83]:
df1.drop('Score5',axis=0)

KeyError: "['Score5'] not found in axis"

In [ ]:
df1.reset_index()
df1


In [ ]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

In [ ]:
df3 = {'Id':[1,2,3,4,5,6,7,8,9,10],'Name':['x','r','z','a','m','e','k','t','u','h'],'weight':[20,30,40,10,4,50,60,23,59,10],'height':[12,1,2,3,42,1,34,32,1,32]}

In [ ]:
df = pd.DataFrame(df3)
df

In [ ]:
df4 = pd.DataFrame(np.random.randn(9,10),index = 'A B C D E F G H I'.split(), columns = 'score1 score2 score3 score4 score5 score6 score7 score8 score9 score10'.split())
df4

In [ ]:
df5 = np.arange(1,10)
df5
x = np.mean(df5)
x

In [ ]:
df5

In [ ]:
y = np.median(df5)
y


In [84]:
arr5 = np.array([4,2,4,3,22,3,3,3,3])
arr5

array([ 4,  2,  4,  3, 22,  3,  3,  3,  3])

In [85]:
z= np.mode(arr5)

AttributeError: module 'numpy' has no attribute 'mode'

In [86]:
e = arr5.mode()
e

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [87]:
from scipy import stats

In [88]:
f = stats.mode(arr5)
f

ModeResult(mode=array([3]), count=array([5]))

In [ ]:
arr3 = np.array([1,2,3,4,5])

In [ ]:
mean_of_arr3 = np.mean(arr3)
mean_of_arr3

In [ ]:
median_of_arr3 = np.median(arr3)
median_of_arr3

In [ ]:
arr4 = np.array([1,2,3,4,5,200])

In [ ]:
mean_of_arr4 = np.mean(arr4)
mean_of_arr4

In [ ]:
median_of_arr4 = np.median(arr4)
median_of_arr4

In [ ]:
arr5 = np.array([1,2,3,4,5])
print(np.var(arr5))

In [ ]:
arr6 = np.array([2,100,79,84,179])
print(np.var(arr6))

In [ ]:
print(np.std(arr6))
print(np.std(arr5))

In [ ]:
arr7 = np.array([2,4,6,8,10])
print(np.std(arr7))